[user_dmytro]
name = "Dmytro"
password = 'jjndskjvksdbknalsnfsdjv'
password = 'jjndskjvksjv'
[user_yaroslav]
name = "Yaroslav"
password = 9876543234567890
[user_artur]
name = "Artur"
password = 'so3i2j38u982whhdbskakjn'
[user_andriy]
name = "Andriy"
password = 'slkglkngjewojngkjsngk'

