[user_dmytro]
name = "Dmytro"
password = 'jjndskjvksdbknalsnfsdjv'
pass = 66666666
[user_yaroslav]
name = "Yaroslav"
password = 9876543234567890
passwords = 'jjjjkkkk'
[user_artur]
name = "Artur"
password = 'so3i2j38u982whhdbskakjn'
[user_andriy]
name = "Andriy"
password = 'slkglkngjewojngkjsngk'

passwords = 9999999

[passwords]
database = 'commonpass'
pass =  'itpass'